/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO 10-07 14:13:45 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:13:46 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
WARNING 10-07 14:13:48 [__init__.py:1750] argument 'guided_decoding_backend' is deprecated
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:48 [api_server.py:1839] vLLM API server version 0.11.1rc1.dev125+gbe22bb6f3
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:48 [utils.py:233] non-default args: {'model_tag': 'Qwen/Qwen2.5-VL-32B-Instruct', 'host': '0.0.0.0', 'model': 'Qwen/Qwen2.5-VL-32B-Instruct', 'dtype': 'bfloat16', 'max_model_len': 16384, 'guided_decoding_backend': 'xgrammar', 'tensor_parallel_size': 8, 'gpu_memory_utilization': 0.98, 'limit_mm_per_prompt': {'image': 10, 'video': 0}, 'mm_processor_kwargs': {'max_pixels': 1003520}, 'disable_chunked_mm_input': True}
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:53 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:53 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
[1;36m(APIServer pid=7)[0;0m `torch_dtype` is deprecated! Use `dtype` instead!
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:53 [model.py:551] Resolved architecture: Qwen2_5_VLForConditionalGeneration
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:53 [model.py:1538] Using max model len 16384
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:53 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=2048.
[1;36m(APIServer pid=7)[0;0m INFO 10-07 14:13:53 [tpu.py:112] [TPU] Forcing DYNAMO_ONCE compilation level, and disabling cudagraph.
[1;36m(APIServer pid=7)[0;0m WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO 10-07 14:13:59 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:00 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
[1;36m(EngineCore_DP0 pid=308)[0;0m INFO 10-07 14:14:01 [core.py:648] Waiting for init message from front-end.
[1;36m(EngineCore_DP0 pid=308)[0;0m INFO 10-07 14:14:02 [core.py:78] Initializing a V1 LLM engine (v0.11.1rc1.dev125+gbe22bb6f3) with config: model='Qwen/Qwen2.5-VL-32B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-VL-32B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=None, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-VL-32B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={'level': 2, 'debug_dump_path': None, 'cache_dir': '', 'backend': 'openxla', 'custom_ops': [], 'splitting_ops': None, 'use_inductor': True, 'compile_sizes': None, 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'use_cudagraph': True, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'full_cuda_graph': False, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_capture_size': None, 'local_cache_dir': None}
[1;36m(EngineCore_DP0 pid=308)[0;0m WARNING 10-07 14:14:02 [multiproc_executor.py:720] Reducing Torch parallelism from 180 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_DP0 pid=308)[0;0m INFO 10-07 14:14:02 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1, 2, 3, 4, 5, 6, 7], buffer_handle=(8, 16777216, 10, 'psm_15b641f0'), local_subscribe_addr='ipc:///tmp/b0b896b0-feb6-4b6b-be97-dfea3eb566a5', remote_subscribe_addr=None, remote_addr_ipv6=False)
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:04 [__init__.py:216] Automatically detected platform tpu.
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:05 [tpu.py:232] tpu_commons not found, using vLLM's TpuPlatform
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 10-07 14:14:06 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
INFO 10-07 14:14:06 [tpu_worker.py:37] tpu_commons not found, using vLLM's TPUWorker.
WARNING 10-07 14:14:07 [tpu.py:168] Pin memory is not supported on TPU.
WARNING 10-07 14:14:07 [tpu.py:168] Pin memory is not supported on TPU.
WARNING 10-07 14:14:07 [tpu.py:168] Pin memory is not supported on TPU.
WARNING 10-07 14:14:07 [tpu.py:168] Pin memory is not supported on TPU.
WARNING 10-07 14:14:07 [tpu.py:168] Pin memory is not supported on TPU.
INFO 10-07 14:14:07 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_498dd250'), local_subscribe_addr='ipc:///tmp/ebad00ad-fa44-4bdf-981e-db2d76c43bc3', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-07 14:14:07 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_df2a9053'), local_subscribe_addr='ipc:///tmp/c1e8326c-7e88-48bd-bff7-a71d3389aa99', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-07 14:14:07 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_1f6b961a'), local_subscribe_addr='ipc:///tmp/93fa0ff6-95e3-425a-86b0-e6caa4fa4677', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-07 14:14:07 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_1ffda55c'), local_subscribe_addr='ipc:///tmp/b79e429d-6439-4728-b742-36d6669fcf14', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-07 14:14:07 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_d2528d9c'), local_subscribe_addr='ipc:///tmp/6549e08a-0363-4064-b1aa-8d662809d4cf', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 10-07 14:14:07 [tpu.py:168] Pin memory is not supported on TPU.
INFO 10-07 14:14:07 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_39887510'), local_subscribe_addr='ipc:///tmp/5dea455d-079a-44e4-8c79-b336ac02ac61', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 10-07 14:14:08 [tpu.py:168] Pin memory is not supported on TPU.
INFO 10-07 14:14:08 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_1c521326'), local_subscribe_addr='ipc:///tmp/8515324b-e2e6-4761-b213-c5f817589a98', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 10-07 14:14:08 [tpu.py:168] Pin memory is not supported on TPU.
INFO 10-07 14:14:08 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_00f1ef6c'), local_subscribe_addr='ipc:///tmp/2e31b61a-a2cf-4389-a498-336b962cbb49', remote_subscribe_addr=None, remote_addr_ipv6=False)
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:09 [tpu_communicator.py:23] tpu_commons not found, using vLLM's TpuCommunicator
INFO 10-07 14:14:09 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:18 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3, 4, 5, 6, 7], buffer_handle=(7, 4194304, 6, 'psm_7fbdc6a1'), local_subscribe_addr='ipc:///tmp/d7f04ca3-589a-4c5e-853b-99aa12ff093e', remote_subscribe_addr=None, remote_addr_ipv6=False)
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:18 [tpu_communicator.py:66] TpuCommunicator initialized with MP
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 3 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 3, EP rank 3
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 0 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 2 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 2, EP rank 2
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 5 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 5, EP rank 5
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 1 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 7 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 7, EP rank 7
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 4 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 4, EP rank 4
INFO 10-07 14:14:18 [parallel_state.py:1208] rank 6 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 6, EP rank 6
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1907] Using exponential token paddings:
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     16
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     32
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     64
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     128
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     256
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     512
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     1024
INFO 10-07 14:14:18 [tpu_model_runner.py:1909]     2048
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] WorkerProc failed to start.
ERROR 10-07 14:14:18 [multiproc_executor.py:597] Traceback (most recent call last):
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 571, in worker_main
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     worker = WorkerProc(*args, **kwargs)
ERROR 10-07 14:14:18 [multiproc_executor.py:597]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 430, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/worker_base.py", line 294, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     self.worker.init_device()  # type: ignore
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_worker.py", line 167, in init_device
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     TPUModelRunner(self.vllm_config, self.device,
ERROR 10-07 14:14:18 [multiproc_executor.py:597]   File "/workspace/vllm/vllm/v1/worker/tpu_model_runner.py", line 200, in __init__
ERROR 10-07 14:14:18 [multiproc_executor.py:597]     assert not self.uses_mrope, "TPU does not support M-RoPE yet."
ERROR 10-07 14:14:18 [multiproc_executor.py:597]            ^^^^^^^^^^^^^^^^^^^
ERROR 10-07 14:14:18 [multiproc_executor.py:597] AssertionError: TPU does not support M-RoPE yet.
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
INFO 10-07 14:14:18 [multiproc_executor.py:558] Parent process exited, terminating worker
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712] EngineCore failed to start.
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712] Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]   File "/workspace/vllm/vllm/v1/engine/core.py", line 703, in run_engine_core
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]   File "/workspace/vllm/vllm/v1/engine/core.py", line 499, in __init__
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]   File "/workspace/vllm/vllm/v1/engine/core.py", line 84, in __init__
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]   File "/workspace/vllm/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]     self._init_executor()
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 106, in _init_executor
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 509, in wait_for_ready
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712]     raise e from None
[1;36m(EngineCore_DP0 pid=308)[0;0m ERROR 10-07 14:14:23 [core.py:712] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
[1;36m(EngineCore_DP0 pid=308)[0;0m Process EngineCore_DP0:
[1;36m(EngineCore_DP0 pid=308)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_DP0 pid=308)[0;0m     self.run()
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_DP0 pid=308)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/workspace/vllm/vllm/v1/engine/core.py", line 716, in run_engine_core
[1;36m(EngineCore_DP0 pid=308)[0;0m     raise e
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/workspace/vllm/vllm/v1/engine/core.py", line 703, in run_engine_core
[1;36m(EngineCore_DP0 pid=308)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=308)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/workspace/vllm/vllm/v1/engine/core.py", line 499, in __init__
[1;36m(EngineCore_DP0 pid=308)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/workspace/vllm/vllm/v1/engine/core.py", line 84, in __init__
[1;36m(EngineCore_DP0 pid=308)[0;0m     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_DP0 pid=308)[0;0m                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/workspace/vllm/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_DP0 pid=308)[0;0m     self._init_executor()
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 106, in _init_executor
[1;36m(EngineCore_DP0 pid=308)[0;0m     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_DP0 pid=308)[0;0m                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=308)[0;0m   File "/workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 509, in wait_for_ready
[1;36m(EngineCore_DP0 pid=308)[0;0m     raise e from None
[1;36m(EngineCore_DP0 pid=308)[0;0m Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
[1;36m(APIServer pid=7)[0;0m Traceback (most recent call last):
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/bin/vllm", line 8, in <module>
[1;36m(APIServer pid=7)[0;0m     sys.exit(main())
[1;36m(APIServer pid=7)[0;0m              ^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/entrypoints/cli/main.py", line 54, in main
[1;36m(APIServer pid=7)[0;0m     args.dispatch_function(args)
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/entrypoints/cli/serve.py", line 57, in cmd
[1;36m(APIServer pid=7)[0;0m     uvloop.run(run_server(args))
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
[1;36m(APIServer pid=7)[0;0m     return __asyncio.run(
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/lib/python3.12/asyncio/runners.py", line 195, in run
[1;36m(APIServer pid=7)[0;0m     return runner.run(main)
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
[1;36m(APIServer pid=7)[0;0m     return self._loop.run_until_complete(task)
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
[1;36m(APIServer pid=7)[0;0m     return await main
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1884, in run_server
[1;36m(APIServer pid=7)[0;0m     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1902, in run_server_worker
[1;36m(APIServer pid=7)[0;0m     async with build_async_engine_client(
[1;36m(APIServer pid=7)[0;0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=7)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/entrypoints/openai/api_server.py", line 180, in build_async_engine_client
[1;36m(APIServer pid=7)[0;0m     async with build_async_engine_client_from_engine_args(
[1;36m(APIServer pid=7)[0;0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=7)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/entrypoints/openai/api_server.py", line 225, in build_async_engine_client_from_engine_args
[1;36m(APIServer pid=7)[0;0m     async_llm = AsyncLLM.from_vllm_config(
[1;36m(APIServer pid=7)[0;0m                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/utils/__init__.py", line 1572, in inner
[1;36m(APIServer pid=7)[0;0m     return fn(*args, **kwargs)
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/v1/engine/async_llm.py", line 207, in from_vllm_config
[1;36m(APIServer pid=7)[0;0m     return cls(
[1;36m(APIServer pid=7)[0;0m            ^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/v1/engine/async_llm.py", line 134, in __init__
[1;36m(APIServer pid=7)[0;0m     self.engine_core = EngineCoreClient.make_async_mp_client(
[1;36m(APIServer pid=7)[0;0m                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
[1;36m(APIServer pid=7)[0;0m     return AsyncMPClient(*client_args)
[1;36m(APIServer pid=7)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/v1/engine/core_client.py", line 769, in __init__
[1;36m(APIServer pid=7)[0;0m     super().__init__(
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/v1/engine/core_client.py", line 448, in __init__
[1;36m(APIServer pid=7)[0;0m     with launch_core_engines(vllm_config, executor_class,
[1;36m(APIServer pid=7)[0;0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=7)[0;0m   File "/usr/local/lib/python3.12/contextlib.py", line 144, in __exit__
[1;36m(APIServer pid=7)[0;0m     next(self.gen)
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/v1/engine/utils.py", line 732, in launch_core_engines
[1;36m(APIServer pid=7)[0;0m     wait_for_engine_startup(
[1;36m(APIServer pid=7)[0;0m   File "/workspace/vllm/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
[1;36m(APIServer pid=7)[0;0m     raise RuntimeError("Engine core initialization failed. "
[1;36m(APIServer pid=7)[0;0m RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
/usr/local/lib/python3.12/multiprocessing/resource_tracker.py:279: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
